apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tdmy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tdmy
    app.kubernetes.io/part-of: byoc-app-ttcy
  name: tdmy
spec:
  rules:
  - host: tdmy-byoc-kbxk-tenant.apps.rhtap-ocp-4-12-amd64-us-east-2-vljxm.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: tdmy
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
